package com.floreantpos.model;
// Generated 15/08/2015 08:56:38 PM by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private int id;
     private Float balance;
     private String idLastAccountMovement;

    public Account() {
    }

	
    public Account(int id) {
        this.id = id;
    }
    public Account(int id, Float balance, String idLastAccountMovement) {
       this.id = id;
       this.balance = balance;
       this.idLastAccountMovement = idLastAccountMovement;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Float getBalance() {
        return this.balance;
    }
    
    public void setBalance(Float balance) {
        this.balance = balance;
    }
    public String getIdLastAccountMovement() {
        return this.idLastAccountMovement;
    }
    
    public void setIdLastAccountMovement(String idLastAccountMovement) {
        this.idLastAccountMovement = idLastAccountMovement;
    }




}


