package com.floreantpos.model;
// Generated 15/08/2015 08:56:38 PM by Hibernate Tools 4.3.1



/**
 * DinerType generated by hbm2java
 */
public class DinerType  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private float discount;

    public DinerType() {
    }

    public DinerType(int id, String name, String description, float discount) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.discount = discount;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public float getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(float discount) {
        this.discount = discount;
    }




}


