package com.floreantpos.model;
// Generated 15/08/2015 08:56:38 PM by Hibernate Tools 4.3.1


import com.floreantpos.model.base.BaseDiner;
import java.util.Date;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Diner generated by hbm2java
 */
@XmlRootElement(name = "diner")
public class Diner  extends BaseDiner {
    
    /*[CONSTRUCTOR MARKER BEGIN]*/
	public Diner() {
		super();
	}

	/**
	 * Constructor for primary key
	 */
	public Diner(java.lang.Integer autoId) {
		super(autoId);
	}

	/**
	 * Constructor for required fields
	 */
	public Diner(java.lang.Integer autoId, java.lang.String password) {

		super(autoId, password);
	}

	/*[CONSTRUCTOR MARKER END]*/

	public final static String DINER_TYPE_RESTAURANT_EMPLOYEE = "RESTAURANT_EMPLOYEE";
	public final static String DINER_TYPE_CUSTOMER_CONTRACTOR = "CUSTOMER_CONTRACTOR";
	public final static String DINER_TYPE_CUSTOMER_EMPLOYEE = "CUSTOMER_EMPLOYEE";
        public final static String DINER_TYPE_OCASSIONAL_CUSTOMER = "OCASSIONAL_CUSTOMER";


     private int id;
     private int idDinerType;
     private int idAccount;
     private String name;
     private String middleName;
     private String lastName;
     private String employeeNumber;
     private String email;
     private Integer nip;
     private Byte isEnabled;
     private Date enabledFrom;
     private Date enabledTo;
     private String cardNumber;

    
	
    public Diner(int id, int idDinerType, int idAccount) {
        this.id = id;
        this.idDinerType = idDinerType;
        this.idAccount = idAccount;
    }
    public Diner(int id, int idDinerType, int idAccount, String name, String middleName, String lastName, String employeeNumber, String email, Integer nip, Byte isEnabled, Date enabledFrom, Date enabledTo, String cardNumber) {
       this.id = id;
       this.idDinerType = idDinerType;
       this.idAccount = idAccount;
       this.name = name;
       this.middleName = middleName;
       this.lastName = lastName;
       this.employeeNumber = employeeNumber;
       this.email = email;
       this.nip = nip;
       this.isEnabled = isEnabled;
       this.enabledFrom = enabledFrom;
       this.enabledTo = enabledTo;
       this.cardNumber = cardNumber;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdDinerType() {
        return this.idDinerType;
    }
    
    public void setIdDinerType(int idDinerType) {
        this.idDinerType = idDinerType;
    }
    public int getIdAccount() {
        return this.idAccount;
    }
    
    public void setIdAccount(int idAccount) {
        this.idAccount = idAccount;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmployeeNumber() {
        return this.employeeNumber;
    }
    
    public void setEmployeeNumber(String employeeNumber) {
        this.employeeNumber = employeeNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getNip() {
        return this.nip;
    }
    
    public void setNip(Integer nip) {
        this.nip = nip;
    }
    public Byte getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(Byte isEnabled) {
        this.isEnabled = isEnabled;
    }
    public Date getEnabledFrom() {
        return this.enabledFrom;
    }
    
    public void setEnabledFrom(Date enabledFrom) {
        this.enabledFrom = enabledFrom;
    }
    public Date getEnabledTo() {
        return this.enabledTo;
    }
    
    public void setEnabledTo(Date enabledTo) {
        this.enabledTo = enabledTo;
    }
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }




}


