/*
 * UserTypeForm.java
 *
 * Created on April 20, 2008, 1:20 AM
 */

package com.floreantpos.ui.forms;

import java.util.Set;

import org.apache.commons.lang.StringUtils;
import org.gjt.sp.jedit.gui.CheckBoxListModel;

import org.gjt.sp.jedit.gui.JCheckBoxList.Entry;

import com.floreantpos.model.UserPermission;
import com.floreantpos.model.UserType;
import com.floreantpos.model.dao.UserTypeDAO;
import com.floreantpos.model.util.IllegalModelStateException;
import com.floreantpos.ui.BeanEditor;
import com.floreantpos.ui.dialog.POSMessageDialog;

/**
 *
 * @author  rodaya
 */
public class DinerTypeForm extends BeanEditor {
    private UserType userType;
    
    /** Creates new form UserTypeForm */
    public DinerTypeForm() {
        this(null);
    }

    public DinerTypeForm(UserType type) {
    	this.userType = type;
    	
    	initComponents();
    	
    	//listPermissions.setModel(UserPermission.permissions);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfTypeName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfDiscount = new javax.swing.JTextField();
        tfDescription = new javax.swing.JTextField();

        jLabel1.setText("Type Name:");

        jLabel2.setText("Description:");

        jLabel3.setText("Discount:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfTypeName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addComponent(tfDiscount))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfDescription;
    private javax.swing.JTextField tfDiscount;
    private javax.swing.JTextField tfTypeName;
    // End of variables declaration//GEN-END:variables

	@Override
	public String getDisplayText() {
		return null;
	}

	@Override
	public boolean save() {
		try {
			if(!updateModel()) {
				return false;
			}
		} catch (IllegalModelStateException e) {
			POSMessageDialog.showError(e.getMessage());
			return false;
		}
		
		UserTypeDAO dao = new UserTypeDAO();
		dao.saveOrUpdate(userType);
		
		return true;
	}

	@Override
	protected boolean updateModel() throws IllegalModelStateException {
		if(userType == null) {
			userType = new UserType();
		}
		
		String name = tfTypeName.getText();
		if(StringUtils.isEmpty(name)) {
			throw new IllegalModelStateException(com.floreantpos.POSConstants.TYPE_NAME_CANNOT_BE_EMPTY);
		}
		
		userType.setName(name);
		userType.clearPermissions();
		
		
		setBean(userType);
		return true;
	}

	@Override
	protected void updateView() {
		if(userType == null) {

			return;
		}
		
		tfTypeName.setText(userType.getName());
		
		Set<UserPermission> permissions = userType.getPermissions();
		if(permissions == null) {

			return;
		}
		
	}

	public UserType getUserType() {
		return userType;
	}

	public void setUserType(UserType userType) {
		this.userType = userType;
		setBean(userType);
		
		updateView();
	}
    
}
